# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
 workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Read input
      id: tsfile
    - uses: ./
      with:
           path: sample1.json

    - name: Echo (content)
      run: echo "${{ steps.tsfile.outputs.content }}"

    - name: Test with pytest
      run: |
        python ./python_script.py
