# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
 workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Read package.json
      id: package
      uses: nizam101nizam/testpython@main
      with:
        path: ./sample1.json
    - name: Echo package.json
      run: echo "${{ steps.package.outputs.content }}"
